[package]
name = "merge-assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
lsp-server = "0.7.8"
lsp-types = "0.97.0"
serde_json = "1.0.140"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
crossbeam-channel = "0.5.15"
rstest = "0.25.0"
